### ISSUE TITLE
[portability] cvui not buildable on Linux

### ISSUE THREAD

**Issue by ebachard** [Dovyski/cvui#12]
OS : Linux, x86_64 / g++ 5.2.1 / Debian like
Using openCV : 3.1.0-dev (checked out and built from sources, without Qt, but using OpenGL)

Problem : currently, cvui is not buildable on Linux, and probably on Mac OS X without some hacks (see below), because vsprintf_s and sprintf_s are Microsoft only, and obviously break everything.

Looks like things work correctly using sscanf, but vsprintf is a bad workaround, allowing only to build, but that's not safe.  Other problems appear because of missing const (will create another issue).

Current workaround to build and make it work consists in: 
`--- a/cvui.cpp
+++ b/cvui.cpp
@@ -9,10 +9,39 @@

 #include <iostream>

+#ifndef MSVC
+#include <stdio.h>
+#include <opencv2/opencv.hpp>
+#define sprintf_s sscanf
+#define vsprintf_s vsprintf
+#else
 #include "opencv2/imgproc.hpp"
 #include "opencv2/highgui/highgui.hpp"
+#endif
 #include "cvui.h"
`

**Comment by Dovyski** [comment]
Fixed by 80f382fdc07a4e784492694effbd2c1fb1fa2fd0.
