### ISSUE TITLE
[Linux] excessive load for the system

### ISSUE THREAD

**Issue by ebachard** [Dovyski/cvui#13]
OS : Linux, x86_64, Debian like
OpenCV : 3.1.0-dev (built from sources)

When running the examples, there is a visible system overload when running a simple main-app, close to 70% on a 2,66 GHz + > 8GB or RAM, what is not normal.

The reason is probably the cv::waitKey(1) eating all the processor time.

Suggestion : using waitKey(10) or even waitKey(20) reduce significantly the load to something between 13% and 17%, what is more cute for a simple example (but can be improved imho).
See the example below (concerns main-app.cpp):

```
@@ -33,7 +39,7 @@ int main(int argc, const char *argv[])
        frame = cv::Scalar(49, 52, 49);

        // Check if ESC key was pressed
-       if (cv::waitKey(10) == 27) {
+       if (cv::waitKey(20) == 27) {
            break;
        }
```

**Comment by Dovyski** [comment]
I've fixed this issue in the [dev branch](https://github.com/Dovyski/cvui/tree/dev) at 172d31ce0862236f3c430ee60998138ad1a3a9f4.

**Comment by ebachard** [comment]
Verified working : the load decreased significantly.

Thanks a lot !
