### ISSUE TITLE
Port cvui to Python

### ISSUE THREAD

**Issue by Dovyski** [Dovyski/cvui#22]
OpenCV already has Python bindings, so it would be a natural thing to port cvui to Python as well. Maybe it is possible to use the C++ code and just create the bindings, or (not ideally) re-write the whole thing in Python.

**Comment by TheMikeyR** [comment]
I can see that 2.5.0 is released, great work! Any updates on the python port?

**Comment by TheMikeyR** [comment]
I've used pybind wrapper in [Intel Realsense](https://github.com/IntelRealSense/librealsense) and it have been "okay" to use, their documentation is not great with the wrappers, but there are just one gigantic file https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/python.cpp which have all definitions so when you need a function described in their cpp version it is pretty much same call in python to do the same.

**Comment by Dovyski** [comment]
That's a great insight, thanks! Regarding Inte Realsense, I've just checked their [docs for the python wrapper](https://github.com/IntelRealSense/librealsense/tree/master/wrappers/python) and there are several steps to build and use it. That's a bit of a pain. I thought it would be easier.

I am more convinced now that a pure Python implementation of cvui will be much better. Just drop `cvui.py` into your project and your are good to go (the same simplicity of a header-only C++ lib).

**Comment by pthom** [comment]
Hi, 

Long time no talk :-)

I happened to have worked with pybind also. I have had to hard-code the conversion between cv::Mat and numpy.ndarray (images are stored as ndarray in python with opencv).

See this gist : this is the conversion routines that I use
https://gist.github.com/pthom/ec2a2395003a2ea004b861d3686ef3fb

cheers,
Pascal

**Comment by TheMikeyR** [comment]
@Dovyski Great that it could help with some insight, in the end I would definitely prefer just to be able to import cvui.py into a project, that way the autocompletion will work wonders :+1:

**Comment by Dovyski** [comment]
@pthom Always a pleasure to see you around ;) Thanks for the gist contribution! Your feedback highlights even more how painful it is to mix C++ and Python code. I will definitely go with a pure Python port of cvui.

@TheMikeyR Yes, me too! And it is an excellent excuse for me to start using Python 😄

**Comment by sfranzyshen** [comment]
pure Python port of cvui :)

**Comment by Sakthi-G33k** [comment]
Guys , any idea on when the python port will be ready? I need to use cvui with python for the project. Is there any chance that you can do a temporary binding for python for people like me to use till the pure python port is ready. Thanks and I will do what I can to help.

**Comment by Dovyski** [comment]
Unfortunately, it is moving way too slow at the moment.

Regarding a temporary binding, I had previously checked [this solution](http://intermediate-and-advanced-software-carpentry.readthedocs.io/en/latest/c++-wrapping.html) and [this one](http://cppyy.readthedocs.io/en/latest/bindings_generation.html) as possible options for cvui bindings. I haven't tried them myself. Maybe you could give them a go and see if they work for your project?

**Comment by Dovyski** [comment]
I'm thrilled to say the python port of cvui is finally complete! :tada: All existing C++ examples were also ported to python. I've added some dummy/wrapper functions in [cvui.py](https://github.com/Dovyski/cvui/blob/dev/cvui.py) to improve code autocompletion in IDEs. Hopefully it will work as intended.

If you happen to be using python in your opencv project, please give the [cvui port](https://github.com/Dovyski/cvui/blob/dev/cvui.py) a spin and help me test it. Just drop [cvui.py](https://github.com/Dovyski/cvui/blob/dev/cvui.py) in your project and you are good to go.

**Comment by Dovyski** [comment]
Python support for cvui has been offically added in version [v2.7.0](https://github.com/Dovyski/cvui/releases/tag/v2.7.0). You can install it using [pip](https://pypi.org/project/cvui/):

```
pip install cvui
```
