### ISSUE TITLE
Typos: cviu

### ISSUE THREAD

**Issue by ngocdaothanh** [Dovyski/cvui#31]
There are many typos `cviu`, please change to `cvui`:
https://github.com/Dovyski/cvui/blob/master/cvui.h

**Comment by Dovyski** [comment]
Thank you for point it out! I will fix as soon as I can.

**Comment by Dovyski** [comment]
Fixed in https://github.com/Dovyski/cvui/commit/b88144fa09d2aa07c9c87eaa21181730f5859a7b.
