### ISSUE TITLE
Can't move trackbar

### ISSUE THREAD

**Issue by papertype** [Dovyski/cvui#34]
I built
https://github.com/Dovyski/cvui/blob/master/example/src/trackbar/main.cpp
with OpenCV 3.4.0 (Official Win pack) and VS2017.

While all the elements are drawn, I can't move trackbars with mouse, at all.

**Comment by Dovyski** [comment]
Thank your for your report. I will check that.

**Comment by papertype** [comment]
Aw sorry, the version I used was 2.0.0. Confirmed 2.5.0-beta solved the issue. Thanks

**Comment by Dovyski** [comment]
There is nothing to be sorry for. I am glad the issue was resolved 😃
