### ISSUE TITLE
Errors when using "dirent.h" beside of "cvui.h"

### ISSUE THREAD

**Issue by AliZ-ee** [Dovyski/cvui#38]
By adding "dirent.h" to the code included "cvui.h", the errors would be raised.
Please check the following repo to see the errors related to this issue:
https://github.com/AliZ-ee/cvui

**Comment by Dovyski** [comment]
Thank you for your report and info on the case. I need some additional info on the problem. Could you please confirm the following, please?

* The `dirent.h` you are referring to is it [this one](https://github.com/tronkko/dirent)?
* Is `dirent.h` included before or after `cvui.h`?

**Comment by Dovyski** [comment]
I've just commited a [possible fix](https://github.com/Dovyski/cvui/commit/aef53d9ce9273399292d11e7166aa94475c62584). Please get the [lastest version of cvui on the dev branch](https://github.com/Dovyski/cvui/tree/dev) and check if your problem was fixed.

**Comment by AliZ-ee** [comment]
Sorry for delay.
* The `dirent.h` that I used is not Linux-compatible version such as [this](https://github.com/tronkko/dirent).
* It has been included before `cvui.h`.

__I've added the latest `cvui.h`, and everything is ok now__
_Thanks_
