### ISSUE TITLE
add #include <Windows.h> 

### ISSUE THREAD

**Issue by lijinhua163** [Dovyski/cvui#43]
visual studio 2015 
add #include <Windows.h> 
Unfortunately, this code doesn't compile.

**Comment by Dovyski** [comment]
Could you please post the compilation error messages?

**Comment by lijinhua163** [comment]
only add <Windows.h>

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2039	“gCurrentContext”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1303	
错误	C2059	语法错误:“)”	main-app	d:\cvui-2.5.0\cvui.h	1122	
错误	C2612	基/成员初始值设定项列表中的非法后缀“)”	main-app	d:\cvui-2.5.0\cvui.h	1122	
错误	C2039	“CLICK”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1283	
错误	C2039	“UP”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1284	
错误	C2039	“DOWN”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1286	
错误	C2039	“IS_DOWN”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1288	
错误	C2039	“gDefaultContext”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1302	
错误	C2065	“gDefaultContext”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1302	
错误	C2065	“gCurrentContext”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1303	
错误	C2039	“gDelayWaitKey”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1304	
错误	C2065	“gDelayWaitKey”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1304	
错误	C2039	“gLastKeyPressed”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1305	
错误	C2065	“gLastKeyPressed”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1305	
错误	C2039	“gContexts”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1311	
错误	C2065	“gContexts”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1311	
错误	C2039	“gCurrentContext”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1313	
错误	C2065	“gCurrentContext”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1313	
错误	C2228	“.empty”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1313	
错误	C2039	“gContexts”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1315	
错误	C2065	“gContexts”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1315	
错误	C2039	“gCurrentContext”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1315	
错误	C2065	“gCurrentContext”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1315	
错误	C2039	“gDefaultContext”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1317	
错误	C2065	“gDefaultContext”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1317	
错误	C2228	“.empty”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1317	
错误	C2039	“gContexts”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1319	
错误	C2065	“gContexts”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1319	
错误	C2039	“gDefaultContext”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1319	
错误	C2065	“gDefaultContext”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1319	
错误	C2039	“error”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1324	
错误	C3861	“error”: 找不到标识符	main-app	d:\cvui-2.5.0\cvui.h	1324	
错误	C2039	“gContexts”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1325	
错误	C2065	“gContexts”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1325	
错误	C2589	“(”:“::”右边的非法标记	main-app	d:\cvui-2.5.0\cvui.h	1347	
错误	C2059	语法错误:“::”	main-app	d:\cvui-2.5.0\cvui.h	1347	
错误	C2589	“(”:“::”右边的非法标记	main-app	d:\cvui-2.5.0\cvui.h	1355	
错误	C2059	语法错误:“::”	main-app	d:\cvui-2.5.0\cvui.h	1355	
错误	C2065	“gStackCount”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1360	
错误	C2065	“gStackCount”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1364	
错误	C2065	“gStack”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1368	
错误	C2065	“gStackCount”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1368	
错误	C2065	“gStack”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1372	
错误	C2065	“gStackCount”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1372	
错误	C2065	“gStackCount”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1377	
错误	C2065	“gStack”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1381	
错误	C2065	“gStackCount”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1381	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	main-app	d:\cvui-2.5.0\cvui.h	1516	
错误	C2143	语法错误: 缺少“,”(在“&”的前面)	main-app	d:\cvui-2.5.0\cvui.h	1516	
错误	C2065	“theParams”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1518	
错误	C2228	“.options”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1518	
错误	C2228	“.step”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1518	
错误	C2065	“theValue”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1519	
错误	C2065	“theParams”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1519	
错误	C2228	“.min”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1519	
错误	C2228	“.step”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1519	
错误	C2065	“theValue”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1521	
错误	C2065	“theParams”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1521	
错误	C2228	“.min”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1521	
错误	C2228	“.step”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1521	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	main-app	d:\cvui-2.5.0\cvui.h	1525	
错误	C2143	语法错误: 缺少“,”(在“&”的前面)	main-app	d:\cvui-2.5.0\cvui.h	1525	
错误	C2065	“thePixelX”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1527	
错误	C2065	“theBounding”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1527	
错误	C2228	“.x”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1527	
错误	C2065	“gTrackbarMarginX”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1527	
错误	C2228	“.width”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1527	
错误	C2065	“theParams”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1529	
错误	C2228	“.min”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1529	
错误	C2228	“.max”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1529	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int	main-app	d:\cvui-2.5.0\cvui.h	1533	
错误	C2143	语法错误: 缺少“,”(在“&”的前面)	main-app	d:\cvui-2.5.0\cvui.h	1533	
错误	C2065	“theValue”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1535	
错误	C2065	“theParams”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1535	
错误	C2228	“.min”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1535	
错误	C2228	“.max”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1535	
错误	C2065	“theBounding”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1537	
错误	C2228	“.x”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1537	
错误	C2065	“gTrackbarMarginX”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1537	
错误	C2228	“.width”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1537	
错误	C2660	“cvui::cvui::internal::getContext”: 函数不接受 0 个参数	main-app	d:\cvui-2.5.0\cvui.h	1542	
错误	C2228	“.mouse”的左边必须有类/结构/联合	main-app	d:\cvui-2.5.0\cvui.h	1542	
错误	C2530	“aMouse”: 必须初始化引用	main-app	d:\cvui-2.5.0\cvui.h	1542	
错误	C2039	“OUT”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1545	
错误	C2039	“DOWN”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1552	
错误	C2039	“OVER”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1554	
错误	C2039	“CLICK”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1560	
错误	C2039	“iarea”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1574	
错误	C2653	“render”: 不是类或命名空间名称	main-app	d:\cvui-2.5.0\cvui.h	1575	
错误	C2665	“cvui::cvui::internal::button”: 7 个重载中没有一个可以转换所有参数类型	main-app	d:\cvui-2.5.0\cvui.h	1575	
错误	C2653	“render”: 不是类或命名空间名称	main-app	d:\cvui-2.5.0\cvui.h	1576	
错误	C3861	“buttonLabel”: 找不到标识符	main-app	d:\cvui-2.5.0\cvui.h	1576	
错误	C2039	“gLastKeyPressed”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1588	
错误	C2065	“gLastKeyPressed”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1588	
错误	C2039	“gLastKeyPressed”: 不是“cvui::cvui::internal”的成员	main-app	d:\cvui-2.5.0\cvui.h	1591	
错误	C2065	“gLastKeyPressed”: 未声明的标识符	main-app	d:\cvui-2.5.0\cvui.h	1591	
错误	C2039	“CLICK”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1597	
错误	C2039	“iarea”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1610	
错误	C2039	“OUT”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1613	
错误	C2653	“render”: 不是类或命名空间名称	main-app	d:\cvui-2.5.0\cvui.h	1613	
错误	C2661	“cvui::image”: 没有重载函数接受 3 个参数	main-app	d:\cvui-2.5.0\cvui.h	1613	
错误	C2039	“OVER”: 不是“cvui::cvui”的成员	main-app	d:\cvui-2.5.0\cvui.h	1614	
错误	C2653	“render”: 不是类或命名空间名称	main-app	d:\cvui-2.5.0\cvui.h	1614	
错误	C2661	“cvui::image”: 没有重载函数接受 3 个参数	main-app	d:\cvui-2.5.0\cvui.h	1614	
错误	C1003	错误计数超过 100；正在停止编译	main-app	d:\cvui-2.5.0\cvui.h	1614	
sorry !

**Comment by Dovyski** [comment]
Thanks for the errors. Is it possible for you to use [cvui 2.7.0-BETA](https://github.com/Dovyski/cvui/releases/tag/v2.7.0-BETA) and check if the problem still happens, please?

**Comment by lijinhua163** [comment]
Version:2.0.0 and  Version: 2.5.0 
Same error

**Comment by Dovyski** [comment]
Same error with version [2.7.0-BETA](https://github.com/Dovyski/cvui/releases/tag/v2.7.0-BETA)?

**Comment by lijinhua163** [comment]
version 2.7.0-BETA is ok.
Thanks!

**Comment by Dovyski** [comment]
Awesome, thank you! I'm closing this issue then. Please open a new one if you find any problem with version 2.7.0-BETA.
