### ISSUE TITLE
cvui.image(frame, theX, theY, theImage) error

### ISSUE THREAD

**Issue by flaviussn** [Dovyski/cvui#44]
When you call `cvui.image(frame, theX, theY, theImage) `

the next error apears:

```
__internal.image(__internal.screen, theX, theY, theImage)
NameError: name 'theX' is not defined
```

Changeint the line 2631 on cvui.py to 

`__internal.image(__internal.screen, aX, aY, aImage)`

it works.

**Comment by Dovyski** [comment]
Thanks for the nice catch! The issue has been fixed: https://github.com/Dovyski/cvui/commit/b64d5278ab05144e52af401c73eb228b2b25e075.
