### ISSUE TITLE
canny in example throw exception with opencv 4.0.1

### ISSUE THREAD

**Issue by ciahua** [Dovyski/cvui#65]
Hi,
when i try to run the canny in your example with opencv 4.0.1, which throws an exception as below:
![image](https://user-images.githubusercontent.com/37827583/50836275-cd7aad00-1393-11e9-8824-8b0efc804902.png)

this happened on
![image](https://user-images.githubusercontent.com/37827583/50836356-00bd3c00-1394-11e9-9ac2-9ec87d5dba78.png)

I don't know how to fix it. could you help me? some other examples work well, some not at the same issue.

**Comment by Dovyski** [comment]
Hi! Sure I can help. What version of cvui are you using?

**Comment by Dovyski** [comment]
I believe the problem has been fixed in the dev version of cvui.
