### ISSUE TITLE
QT window's toolbar

### ISSUE THREAD

**Issue by galdalali** [Dovyski/cvui#73]
When creating a window using init 
`cvui::init(WINDOW_NAME, 1);`
with opencv compiled with QT the [window's toolbar](https://docs.opencv.org/2.4/modules/highgui/doc/qt_new_functions.html) is shown
Is there any way to disable it?

**Comment by Dovyski** [comment]
`cvui::init()` will create a regular OpenCV window without any toolbars. I am afraid your problem is related to Qt itself, which I am not familiar with. Have you checked if there is a way to change the properties of the window using the Qt API?
