### ISSUE TITLE
cvui::button function always return a value even i do not click it， this will make the cpu loading is  high

### ISSUE THREAD

**Issue by lileilei-camera** [Dovyski/cvui#76]

**Comment by Dovyski** [comment]
`cvui::button()` is designed to return a value always (it changes to `true` when the button is pressed). I think your high CPU loading is due to another thing. Are you using cvui's keyboard shortcuts, i.e. call `cvui::init(WINDOW_NAME, 20);` instead of `cvui::init(WINDOW_NAME);` ?
