### ISSUE TITLE
Getting compiling error in cvui.h in Linux platform

### ISSUE THREAD

**Issue by prabhakarmp** [Dovyski/cvui#82]
Hi 

It is working great in windows.

When I try to run the same in Ubuntu it is giving error.

Platform: Ubuntu 16
Opencv: 3.4.0

![CVUI_ERROR](https://user-images.githubusercontent.com/30103823/62681247-e1909680-b9d6-11e9-863d-836f55ef3940.jpg)

I am new to cvui.  Please help me sort it out.

Thanks and Regards,
Prabhakar M

**Comment by Dovyski** [comment]
Hi and thank you for using cvui! The error you reported seems to be a problem with your compiler. You can try: 

a) Compile your project with a more recent compiler;
b) Use  `g++` command to compile your project using `-std=c++11` or  `-std=c++0x`. E.g.:

```bash
g++ -std=c++0x *.cpp -o output
```

**Comment by prabhakarmp** [comment]
Hi Dovyski

Thank you. It is working now.


Regards,
Prabhakar M

**Comment by Dovyski** [comment]
Great! Feel free to open a new issue if you find any problems or have more questions.
