### ISSUE TITLE
The interactive layer is separated from the visual layer

### ISSUE THREAD

**Issue by jimmymeister98** [Dovyski/cvui#89]
![Capture](https://user-images.githubusercontent.com/44345551/74663175-9502f080-519b-11ea-800b-0ab392648338.PNG)
Win 10 (64bit)
Vs 2017
Opencv 4.2.0
latest release of cvui
Hi, i really love your cvui but upon launch my visual and interactive layer separate and the plain grey interactive layer blocks the visual layer.The buttons on the visual layer dont work, but if i click on the respective positions on the interactive layer the buttons work just fine, but i obviously can't see where i am clicking.
I didnt find anyone with similiar problems, so i thought that i'll get some help over here :/

**Comment by Dovyski** [comment]
Hi and thank you for your interested on cvui!

I am sorry, but I did not fully understand the problem. Do you have one or multiple windows running in your app? Are you using `cvui::iarea()` to detect interactions in an specific area (layer, as you say)?

**Comment by jimmymeister98** [comment]
Oh, not yet. Thanks in advance! I've written my own mouse listener, but i'll try to implement the function tomorrow and let you know if it fixed it.
And i have only one window running in my application.

**Comment by jimmymeister98** [comment]
Okay, i fixed it, i reversed back to Opencv 3.4.9 and moved the whole project to a new solution. There was an internal error somewhere deep in my project. I fixed it, im sorry that it my issue was rather unnecessary.

Anyways, i wanted to test cvui with your code from ([https://github.com/Dovyski/cvui/tree/master/example/src/complext-layout](url)) and it gives an assertion failiure.

Closed because fixed, thanks for the quick response and for the awesome lib!!!

**Comment by Dovyski** [comment]
I am glad you managed to find a solution for your problem! I'll check the bug you reported. Thanks!
